### PR TITLE
SONARJAVA-1614 Handle lombok annotations generating equals() methods

### PR DESCRIPTION
**Pull request by thomasturrell**
This replaces pull request https://github.com/SonarSource/sonar-java/pull/752

Comments actioned, squashed commits and used Jira issue for all commits and pull request

### CODE REVIEW

**Comment by thomasturrell** [comment]
@m-g-sonar hopefully this is a better pull request.  Sorry I'm not so familiar with git so I thought it would be faster for me to simply create a new pull request.  Apologies that I took so long to action.

**Comment by m-g-sonar** [comment]
Hey @thomasturrell!

No worries, that's perfect! Thanks a lot for your contribution!

**Comment by m-g-sonar** [comment]
Merged on master! https://github.com/SonarSource/sonar-java/commit/c554a6da1524b8da517c363c571b6bed4993fc68
Thanks again! :)

**Comment by thomasturrell** [comment]
Great thank you. I'm proud to have made a small contribution to really good tool.

**Pull request merged**
