### PR TITLE
SONARJAVA-3273 RSPEC-5301 "ActiveMQConnectionFactory" should not be vulnerable to malicious code deserialization

### PR DESCRIPTION
**Pull request by parrot55**
…ionFactory

Please ensure your pull request adheres to the following guidelines: 

- [ ] Use the following formatting style: [SonarSource/sonar-developer-toolset](https://github.com/SonarSource/sonar-developer-toolset#code-style)
- [ ] Unit tests are passing and you provided a unit test for your fix
- [ ] ITs should pass : To run ITs locally, checkout the [README](https://github.com/SonarSource/sonar-java/blob/master/README.md) of the project.
- [ ] If there is a [Jira](http://jira.sonarsource.com/browse/SONARJAVA) ticket available, please make your commits and pull request start with the ticket number (SONARJAVA-XXXX)

### CODE REVIEW

**Comment by alban-auzeill** [comment]
Hi @parrot55, I have created a new PR #2773 with your commit directly in sonar-java repository to trigger our internal CI.

I also added a new commit "Fix from review, enforce call to setTrustedPackages" (see #2773) with some changes:

**1)** I always raise an issue if there's no call to `setTrustedPackages`
In your PR the rule were raising an issue for:
```
ActiveMQConnectionFactory factory = new ActiveMQConnectionFactory("tcp://localhost:61616"); // Noncompliant
return factory;
```
And not for:
```
ActiveMQConnectionFactory factory = new ActiveMQConnectionFactory("tcp://localhost:61616");
factory.setTrustAllPackages(false);
return factory;
```
But `trustAllPackages` is `false` by default and calling `factory.setTrustAllPackages(false);` changes nothing. IMO, the rule should have the same behavior in both above cases.

**2)** I try to detect when `setTrustedPackages` is used with `"*"`
```
factory.setTrustedPackages(Arrays.asList("*"));
```
Because it means trust all packages in this logic [ClassLoadingAwareObjectInputStream.java#L98](https://github.com/apache/activemq/blob/master/activemq-client/src/main/java/org/apache/activemq/util/ClassLoadingAwareObjectInputStream.java#L98)


Could you give me your feedback about those changes?
Do you allow me to amend my changes into your commit?

**Comment by alban-auzeill** [comment]
After 6 days without answers, I assume it's a yes. I'm closing this PR and I will merge #2773.

**Comment by parrot55** [comment]
Hi Alban,

Sorry, I replied to the mail I received from Github, apparently it hasn't reached. Anyway, I agreed with your comments, so no difference. Thank you for merging.

Cheers,
Patrick

**Comment by alban-auzeill** [comment]
Hi Patrick (@parrot55),
I learned something, next time I ask a question that requires an answer, I will add the note `do not answer by email` :wink: 
Thanks for your contribution, it will be available in SonarJava 6.1
Cheers,
Alban

**Pull request closed without merging**
