### PR TITLE
SONARJAVA-1924 FP on Rule S1450 when using @Getter Lombok annotation …

### PR DESCRIPTION
**Pull request by fergarrui**
* Ignoring annotated private fields.
* White list removed.

### CODE REVIEW

**Comment by m-g-sonar** [comment]
Hello @fergarrui,
This JIRA ticket is planned for version 4.4 of the Java Analyzer. So I'll review in details after release of 4.3. Before going further, however, you may want to change your fix. The idea of the ticket is to ignore any unused private field as soon as the field is annotated. The correct way to fix it would then be to remove completely the white list.

Cheers,

**Comment by fergarrui** [comment]
Hi @m-g-sonar, true, my bad. New commit added :)

**Comment by m-g-sonar** [comment]
Hey @fergarrui !
Thanks a lot for your contribution!

Just one thing: I amended the description of the rule in order to explicitly mention that any annotated field is now ignored (see the exception part in [RSPEC-1450](https://jira.sonarsource.com/browse/RSPEC-1450) and [RSPEC-1840](https://jira.sonarsource.com/browse/RSPEC-1840)), as it's an important detail about the implementation. I let you update the description of the rule accordingly.

Once done, everything looks perfectly fine to me, and I'm going to merge it as soon as version 4.3 is released.

Cheers,
Michael

**Comment by m-g-sonar** [comment]
On a second thought, forget my comment about the description. We will handle the update of the description at the end of the sprint, in order to deal in one batch with all the description modifications! :)

So nothing to do on this one, everything is alright and I'll merge as soon as we release!

Cheers,
Michael

**Comment by fergarrui** [comment]
Thanks for your feedback :)

**Pull request merged**
