### PR TITLE
Regular expression rule template for checking for architectural constraints

### PR DESCRIPTION
**Pull request by cardil**
A source code comply to an architectural model when it fully adheres to a set of architectural constraints. A constraint set with regular expression allows to deny various code conventions, or to force them.

You can for instance use this rule to :

 * Force using given format of error codes ex.: `new ErrCode\((?!"[A-Z]{2}-[0-9]{6}").*\);`
 * Deny using given code ex.: `@ManagedBean`

### CODE REVIEW

**Comment by Cosaquee** [comment]
:+1:

**Comment by MattAgile** [comment]
:+1:

**Comment by adko-pl** [comment]
:+1:

**Comment by benzonico** [comment]
Thanks for your pull request. 

Unfortunately I don't see a big value out of this rule as a rule for the java plugin. This check has absolutely no dependency on the java language in fact. I tend to think this could eventually be valuable as a rule template in a dedicated plugin rather than a java rule in the java plugin.  By doing so you would be able to actually configure on which kind of file you want to match the searched expression and not only limit that to java file. 

Moreover, such generic rules goes against what we are trying to achieve in terms of zero configuration by providing a rule that is way too generic.

With those arguments in mind I am closing this pull request. 
Thanks again for your contribution.

**Comment by cardil** [comment]
That's unfortunate. That's rule is in fact a template and shouldn't  be active by default like architectural constraints rule that is present now in sonar. It's meant to be replacement for checkstyle regex rule. I can't finally dump chceckstyle unless a rule template like this.

Yup. This can be generic rule but easy of configuration for java file can speak to place it here.

If you are not convinced I will just publish a micro plugin for sonar with this rule

**Comment by benzonico** [comment]
When we reimplemented checkstyle rules we had a look at those regexp rule and decided to skip it as it is too generic in our opinion and not particularly dedicated to Java language. 

Therefore we really think there would be value by having those as a dedicated plugin. More especially given that would allow to actually define this rule for several languages and not only Java. 

Feel free to implement this as a separate plugin and reach the sonarqube google group ( https://groups.google.com/forum/#!forum/sonarqube ) to announce your contribution to SonarQube ecosystem. 

Cheers,

**Pull request closed without merging**
