### PR TITLE
SONARJAVA-927 Annotations on enum constant is not available in SyntaxTree

### PR DESCRIPTION
**Pull request by merciesa**

### CODE REVIEW

**Comment by benzonico** [comment]
Should I review it already ?

**Comment by merciesa** [comment]
Yes please, apart from the commit message ;)

**Comment by merciesa** [comment]
This is indeed an interesting case. There are two constructs, AnnotationTree and ModifierTree.

from the types: AnnotationTree extends ModifierTree
but: List<AnnotationTree> and List<ModifierTree> are unrelated

from the grammar: EnumConstant can only have a list of annotations (not modifiers)
Still, annotations in EnumConstant are represented by ModifiersTree.

Hence, a cast is required because ModifiersTree expects a List<ModifierTree> and not a List<AnnotationTree>.

The only risk here is if a ModifierTree is added to the list and accessed with the original type. But in practice this should not happen, because the original type is lost during construction of ModifiersTree.

**Comment by merciesa** [comment]
But we could make a copy if you feel safer:
ModifiersTreeImpl modifiers = modifiers(annotations.isPresent() ? Optional.<List<ModifierTree>>of(new ArrayList(annotations.get())) : Optional.<List<ModifierTree>>absent());

EnumConstantTreeImpl result = new EnumConstantTreeImpl(modifiers, identifier, newClass);

**Comment by benzonico** [comment]
Let's go for this one, but that would probably require some refactoring at some point.

**Pull request closed without merging**
