### PR TITLE
SONARJAVA-4244 S3400 should report on boolean types

### PR DESCRIPTION
**Pull request by kaufco**

### CODE REVIEW

**Review by dorian-burihabwa-sonarsource — APPROVED** [review]
LGTM 👍🏿

**Review by dorian-burihabwa-sonarsource — CHANGES_REQUESTED** [review]
I approved before realizing that the ruling is broken. Let's have a look together

**Comment by kobayami** [comment]
Fixed.

**Review by dorian-burihabwa-sonarsource — APPROVED** [review]
LGTM 👍🏿

**Pull request merged**
