### PR TITLE
SONARJAVA-728 JaCoCo Listeners should support surefire reuseForks=false

### PR DESCRIPTION
**Pull request by fjakop**
I've added a workaround by getting the `IAgent` lazily. Seems to wor for me.

### CODE REVIEW

**Comment by benzonico** [comment]
Hi @fjakop,

Thanks for the PR.
isn't that redundant with https://github.com/SonarSource/sonar-java/pull/324 ? 
As is it is pretty hard to review this PR as there are abolutely no modification or addition on tests (therefore how can we be sure what does this PR fixes ?) and formatting seems to be a bit odd on your commit which makes review very hard.
Please make your commit minimal and add some unit tests. 

Thanks.

**Comment by fjakop** [comment]
Hi @benzonico,
yes, this is kind of redundant, but I did not notice PR #324 because there was nothing commented on 	SONARJAVA-728 in Jira.
I've fixed the formatting and added a test, which ensures that the `IAgent` is not loaded at construction time of `JacocoController`. 
This fix does not change any public API, so select for yourself what to do with it. We just need a working `reuseForks=false`, no matter which fix does it :-)

**Comment by fjakop** [comment]
Hi @benzonico,

is there anything left to do for me? If so, please let me know.

Thanks.

**Comment by fabdouglas** [comment]
I've created a new PR #1317 based on #324

**Comment by benzonico** [comment]
Closing this one and relying on latest opened. Thanks for the contribution.

**Pull request closed without merging**
