### PR TITLE
SONARJAVA-4598 - FP on S2259 when CollectionUtils and MapUtils are used from commons3

### PR DESCRIPTION
**Pull request by rguihard**
[Issue link](https://sonarsource.atlassian.net/browse/SONARJAVA-4598)

Append missing behaviors in org.apache.commons.collections.json

org.apache.commons.collections.MapUtils#size(Ljava/util/Map;)I 
org.apache.commons.collections.CollectionUtils#size(Ljava/lang/Object;)I org.apache.commons.collections.CollectionUtils#isNotEmpty(Ljava/util/Collection;)Z org.apache.commons.collections.MapUtils#isEmpty(Ljava/util/Map;)Z org.apache.commons.collections.MapUtils#isNotEmpty(Ljava/util/Map;)Z

Please ensure your pull request adheres to the following guidelines: 

- [X] Use the following formatting style: [SonarSource/sonar-developer-toolset](https://github.com/SonarSource/sonar-developer-toolset#code-style)
- [X] Unit tests are passing and you provided a unit test for your fix
- [x] ITs should pass : To run ITs locally, checkout the [README](https://github.com/SonarSource/sonar-java/blob/master/README.md) of the project.
- [X] If there is a [Jira](http://jira.sonarsource.com/browse/SONARJAVA) ticket available, please make your commits and pull request start with the ticket number (SONARJAVA-XXXX)

### CODE REVIEW

**Review by kaufco — CHANGES_REQUESTED** [review]
Hi @rguihard , thanks for your contribution! This looks good to me. Could you please:

- rebase on current head of master
- resolve the conflicts

Then it should be ready for merge.

**Comment by rguihard** [comment]
It should be ok now

**Review by kaufco — APPROVED** [review]

**Comment by kaufco** [comment]
Hi @rguihard , your PR was merged. Thanks for the good work!

Note: the actual merge happened in [PR 4632](https://github.com/SonarSource/sonar-java/pull/4632), which mirrors your original PR. This is required in order to trigger our CI correctly.

Best,
Marco

**Comment by rguihard** [comment]
Thanks for your work 

Have a nice day

**Pull request closed without merging**
