### PR TITLE
SONARJAVA-1067 Symbol not found now has unknown owner instead of null

### PR DESCRIPTION
**Pull request by m-g-sonar**
`JavaSymbol.owner()` is not marked with `@CheckForNull`, nor `JavaSymbol.owner`. I prefered to force the unknown symbol as owner in case of ambiguity and not found symbol.

### CODE REVIEW

**Comment by SonarTech** [comment]
SonarQube analysis reported no new issues.

**Comment by benzonico** [comment]
Test of this is only indirect. You should have a dedicated test into `SymbolTableTest` class.

**Comment by benzonico** [comment]
LGTM.

**Comment by SonarTech** [comment]
SonarQube analysis reported no new issues.

**Pull request closed without merging**
