### PR TITLE
Fix message when using File.delete

### PR DESCRIPTION
**Pull request by dpursehouse**
The message says to use "java.nio.Files#delete" but should
be "java.nio.file.Files#delete".

Change-Id: I1bcb25ef70fb6a48c82dfa5cc38c0efd12cb684a
Signed-off-by: David Pursehouse <dpursehouse@collab.net>

Please ensure your pull request adheres to the following guidelines: 

- [ ] Use the following formatting style: [SonarSource/sonar-developer-toolset](https://github.com/SonarSource/sonar-developer-toolset#code-style)
- [ ] Unit tests are passing and you provided a unit test for your fix
- [ ] ITs should pass : To run ITs locally, checkout the [README](https://github.com/SonarSource/sonar-java/blob/master/README.md) of the project.
- [ ] If there is a [Jira](http://jira.sonarsource.com/browse/SONARJAVA) ticket available, please make your commits and pull request start with the ticket number (SONARJAVA-XXXX)

### CODE REVIEW

**Comment by dpursehouse** [comment]
I'm not sure why "SonarQube Code Analysis" has not completed yet.

**Comment by quentin-jaquier-sonarsource** [comment]
Hello, 
I created [SONARJAVA-3302](https://jira.sonarsource.com/browse/SONARJAVA-3302), to include this fix into SonarJava 6.2.

SonarQube Analysis (and a few other checks) are not triggered for external PR, I therefore created a PR #2840 .

I will merge it as soon as everything is ready on the other PR.

Thanks for spotting this inconsistency.

**Comment by dpursehouse** [comment]
@quentin-jaquier-sonarsource thanks for taking care of this.

I've created an account on jira but I can't seem to find where to report issues.  Am I missing something?

**Comment by quentin-jaquier-sonarsource** [comment]
For small fixes such as this one, directly opening a PR is fine in my opinion.

If you want to report issues, get help, suggest improvement and a lot of other things, the main point of contact is **[community.sonarsource.com](https://community.sonarsource.com/)**. Be sure to use the correct **categories** and **tags** (especially java), to be sure to reach the correct people.

You should use Jira mainly for tracking the progress (watching or voting for an issue), or eventually commenting an existing ticket, but you can not report issues there.

**Pull request closed without merging**
