### PR TITLE
SONARJAVA-1242 : 'final' variable exclusion & '\0' char support

### PR DESCRIPTION
**Pull request by axel3rd**
Hi, 

Proposal for [SONARJAVA-1242](https://jira.sonarsource.com/browse/SONARJAVA-1242) complement (#382)

Feature :
- ``'\0'`` *char* support
- Exclude ``final`` variables (compilation problem otherwise)

Best regards

### CODE REVIEW

**Comment by axel3rd** [comment]
I will check Guava ITS and I come back ...

**Comment by axel3rd** [comment]
**Known limitation** : The [Binary Literal](http://docs.oracle.com/javase/7/docs/technotes/guides/language/binary-literals.html) 0 does not raise an issue (I didn't found a reliable parsing) :
```
long l = 0b00000000_00000000_00000000_00000000;
```

**Comment by mpaladin** [comment]
@axel3rd I reopened ticket [SONARJAVA-1242](https://jira.sonarsource.com/browse/SONARJAVA-1242) to merge your PR, will be done before release.

**Comment by axel3rd** [comment]
> I reopened ticket SONARJAVA-1242 to merge your PR, will be done before release.

@mpaladin  Thanks.

**Comment by mpaladin** [comment]
@axel3rd merged with slight modification.

**Comment by axel3rd** [comment]
Ok, thanks.

**Pull request closed without merging**
