### PR TITLE
SONARJAVA-1681 / SONARJAVA-1776: Handle this assignments and exclude JPA entities.

### PR DESCRIPTION
**Pull request by Johnnei**
Please ensure your pull request adheres to the following guidelines: 
- [x] Use the following formatting style: [SonarSource/sonar-developer-toolset](https://github.com/SonarSource/sonar-developer-toolset#code-style)
- [x] Unit tests are passing and you provided a unit test for your fix
- [x] ITs should pass : To run ITs locally, checkout the [README](https://github.com/SonarSource/sonar-java/blob/master/README.md) of the project.
- [x] If there is a [Jira](http://jira.sonarsource.com/browse/SONARJAVA) ticket available, please make your commits and pull request start with the ticket number (SONARJAVA-XXXX)

Also solves SONARJAVA-1776.

### CODE REVIEW

**Comment by manuel-uberti** [comment]
Any updates on this one? Will it be merged?

Thanks.

**Comment by benzonico** [comment]
Hi @manuel-uberti , this PR should be reviewed (and hopefully merged) during the current sprint.

**Comment by manuel-uberti** [comment]
Great, thanks. 👍

**Comment by Johnnei** [comment]
Looks like my attempt to resolve the merge conflict and restore the this-assignment handling broke several ITs. Will have a good look at this tomorrow as I also feel like my current way to resolve the assignment changes aren't that clean either.

**Comment by Johnnei** [comment]
This now partially reverts fcd94cb2c44562d4cf7fb3c1a6b76efdeec86ed9 as with handling the this assignments I need to cover both cases. I've been trying (on earlier merge conflicts) to 'promote' the MEMBER_SELECT to a simple assignment but that caused several FPs which I couldn't manage to fix.

**Comment by Johnnei** [comment]
Thanks @m-g-sonar for the thorough explanation of the issues, this really helps me understand how to interact properly with the API. The explanation of my mistake in the this assignment fully explains the weird FPs as they were all incorrect member selects. I should have also realized that if it were that simple you guys would already have done it. I will also take blame for merging these two tickets where as it probably would have been wiser to 'link' these issues and depending on merge order correct the newly fixed FPs.
I'll extract the code for [SONARJAVA-1977](https://jira.sonarsource.com/browse/SONARJAVA-1977) into a new PR. I'll also try to make something for the other tickets as I love the challenge :smile:

Also no worries about the delay. Every now and then I peek at the Java Team board and always saw these tickets around so I knew they were still in the pipeline. I'm also very curious to see the Stack/Graph viewers in action as I commonly had issues with keeping track of what is what.

**Pull request closed without merging**
