### PR TITLE
SONARJAVA-547 Add brackets tokens to ParameterizedTypeTree

### PR DESCRIPTION
**Pull request by m-g-sonar**

### CODE REVIEW

**Comment by SonarTech** [comment]
SonarQube analysis reported no new issues.

**Comment by benzonico** [comment]
2 things :  
  - Maybe a test with multiple type arguments could be a nice improvement.
  - Have you consider the comma token ?

**Comment by m-g-sonar** [comment]
Ok, I'll improve the tests to test it with multiple arguments. Regarding management of the comma, it will not be done now. I'll update the SONARJAVA-547 ticket to keep it in mind.

**Comment by SonarTech** [comment]
SonarQube analysis reported no new issues.

**Pull request merged**
