### PR TITLE
SONARJAVA-1009 Rule: S2391 JUnit framework methods should be declared…

### PR DESCRIPTION
**Pull request by mpaladin**
@benzonico I would like your opinion about StringUtils.getLevenshteinDistance usage.

### CODE REVIEW

**Comment by SonarTech** [comment]
SonarQube analysis reported 2 new issues:
* 2 major

Details:
* Use isEmpty() to check whether the collection is empty or not. (org.codehaus.sonar-plugins.java:java-checks:src/main/java/org/sonar/java/checks/JunitMethodDeclarationCheck.java) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1155)
* Use isEmpty() to check whether the collection is empty or not. (org.codehaus.sonar-plugins.java:java-checks:src/main/java/org/sonar/java/checks/JunitMethodDeclarationCheck.java) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1155)

**Comment by SonarTech** [comment]
SonarQube analysis reported 2 new issues:
* 2 major

Details:
* Use isEmpty() to check whether the collection is empty or not. (org.codehaus.sonar-plugins.java:java-checks:src/main/java/org/sonar/java/checks/JunitMethodDeclarationCheck.java) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1155)
* Use isEmpty() to check whether the collection is empty or not. (org.codehaus.sonar-plugins.java:java-checks:src/main/java/org/sonar/java/checks/JunitMethodDeclarationCheck.java) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1155)

**Comment by benzonico** [comment]
Looks good to me. 

I have absolutely no knowledge of `getLevenshteinDistance` method. AFAI undertand the main drawback it has is that it have bad complexity (exponential). This means that we probably should check for methods with big names and how the algorithm reacts to prevent us from failing in some corner cases (or check the size of string before feeding it to the `getLevenshteinDistance` )

**Comment by SonarTech** [comment]
SonarQube analysis reported no new issues.

**Comment by SonarTech** [comment]
SonarQube analysis reported no new issues.

**Comment by SonarTech** [comment]
SonarQube analysis reported no new issues.

**Pull request merged**
