### PR TITLE
SONARJAVA-1579: Add support for all method overloads

### PR DESCRIPTION
**Pull request by liorsamuni**
Add the option to ignore all method signatures when writing a custom rule based on the 'DisallowedMethodCheck' rule

### CODE REVIEW

**Comment by benzonico** [comment]
Hi thanks for the contribution. Looking (very) quickly at it, it seems ok but could you please make sure the formatting is correct in order to ease the review and not commit format changes. 
You can use this project for formatting : https://github.com/SonarSource/sonar-developer-toolset 

Thanks.

**Comment by liorsamuni** [comment]
Hi,
I've reformatted the file as you have asked for.

Thanks.

**Comment by benzonico** [comment]
Hi, Thanks for the modification. This is far clearer to review. This looks good to me.
Would you be able to do two last very small things before I merge your PR : 
 - Change the parameter description to : if true, check only name and type definition of method, ignoring arguments.
 - Squash your commits to have only one commit with a name starting with : SONARJAVA-1579 ( https://jira.sonarsource.com/browse/SONARJAVA-1579 )

Thanks for the quality of the contribution.

**Comment by benzonico** [comment]
In fact for the parameter this suggestion is much better (thanks  @ganncamp )

key: allOverloads
default: false
description: Set to true to flag all overloads regardless of parameter type

Thanks.

**Comment by benzonico** [comment]
Thanks again for the quality of your contribution ! I rebased things on master (Github does not allow to merge with FF) so it is now in master https://github.com/SonarSource/sonar-java/commit/e5a033cf7aca8de0a4bff9d4ff6781a66f286e29 

Therefore I am closing this pull request.

**Pull request closed without merging**
