### PR TITLE
SONARJAVA-73 add more lombok's used annotations for UnusedPrivateFieldCheck

### PR DESCRIPTION
**Pull request by liudongmiao**
Add more used annotation from lombok.

Getter/Setter: http://projectlombok.org/features/GetterSetter.html
Data: http://projectlombok.org/features/Data.html
Value: http://projectlombok.org/features/Value.html
Builder: http://projectlombok.org/features/Builder.html
ToString: http://projectlombok.org/features/ToString.html
EqualsAndHashCode: http://projectlombok.org/features/EqualsAndHashCode.html
NoArgsConstructor, RequiredArgsConstructor, AllArgsConstructor: http://projectlombok.org/features/Constructor.html

Won't supported:
Synchronized  with customed name:  http://projectlombok.org/features/Synchronized.html

### CODE REVIEW

**Comment by SierraGolf** [comment]
+1

**Comment by augusto** [comment]
+1

**Comment by fedy2** [comment]
+1

**Comment by benzonico** [comment]
Hi to all, 
Thanks for your contribution.
This seems a cool feature but one thing is :  what are we talking about ? 

Can someone provide a simple but really clear explanation of what this pull request is trying to achieve, so I can associate this with a proper jira ticket and we can handle this PR in next java sprint ? 

Thanks

**Comment by liudongmiao** [comment]
@benzonico As there are links for every annotation, so here I write only for @Getter/Setter.
For example, if we defines a POJO like this (normally json):

    public class POJO {
        public Number minPrice;
        public Number maxPrice;
        public String title;
        public int id;
    }

Of course, we find above codes are not acceptable, so we may want to add the Getter/Setter, and change the public to private, probably like this:

    public class POJO {
        private Number minPrice;
        private Number maxPrice;
        private String title;
        private int id;

        public Number getMinPrice() {
            return this.minPrice;
        }

        public void setMinPrice(Number minPrice) {
            this.minPrice = minPrice;
        }

        public Number getMaxPrice() {
            return this.maxPrice;
        }

        public void setMaxPrice(Number maxPrice) {
            this.maxPrice = maxPrice;
        }

        public int getId() {
            return this.id;
        }

        public void setId(int id) {
            return this.id = id;
        }

        public String getTitle() {
            return this.title;
        }

        public void setTitle(String title) {
            this.title = title;
        }
    }

But above codes are very complex, and we only want to define several attributes.
lombok want to simplify these codes, as normally these Getter/Setter are very simple, so above codes can simple be (lombok can add some dummy method automatically)

    @Getter
    @Setter
    public class POJO {
        private Number minPrice;
        private Number maxPrice;
        private String title;
        private int id;
    }

Or 

    @Data // @Data add more than @Getter/@Setter
    public class POJO {
        private Number minPrice;
        private Number maxPrice;
        private String title;
        private int id;
    }

But sonar doesn't recogize @Data/@Setter/@..., only @Getter after sonar-java 2.8.

**Comment by benzonico** [comment]
Hi, and thanks again,
Ticket created : http://jira.codehaus.org/browse/SONARJAVA-990 
This pull request will be reviewed and merged or closed during next sprint.

**Comment by SierraGolf** [comment]
:+1:

**Comment by erikvaningen** [comment]
+1

**Comment by marcegarba** [comment]
+1

**Comment by alexnederlof** [comment]
:+1:

**Comment by Librael** [comment]
Hi everybody,
I am using SonarQube 4.5.4 with java plugin 3.1. As I know this sonar-java version supports lombok partially (Getter and Setter annotations).
But in my case it still recognize lombok.Getter as squid:S1068  "Unused private fields should be removed":
@Getter
private String userName;

Do you have any ideas why this could happen and where can I fix it?
Thank you!

**Comment by benzonico** [comment]
@Librael please post your question to the user mailing list : http://www.sonarqube.org/get-support/ This PR is not the place to discuss this.

**Comment by darxriggs** [comment]
+1

Any progress on this?

**Comment by fabdouglas** [comment]
+1

**Comment by benzonico** [comment]
This will be handled via https://github.com/SonarSource/sonar-java/pull/257 

As a consequence I close this PR. Thanks for your contribution !

**Comment by tanjiquan** [comment]
image
this problem has resolve？

**Comment by m-g-sonar** [comment]
Please do not post on **closed** Pull request, and reach us using our community forum. Please also make sure to follow guidelines and provide all the information requested.
https://community.sonarsource.com/

**Comment by SethiHemanshu** [comment]
Has this issue resolved?

**Pull request closed without merging**
