### PR TITLE
SONARJAVA-1391 - SE: |= and &= assignements should correctly propagat…

### PR DESCRIPTION
**Pull request by DidierBesset**
…e constraints

### CODE REVIEW

**Comment by SonarTech** [comment]
SonarQube analysis reported 1 issue:
* MAJOR 1 major

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* MAJOR [The Cyclomatic Complexity of this method "createSymbolicValue" is 12 which is greater than 10 authorized.](https://github.com/SonarSource/sonar-java/blob/38308d8116f6b52c9328274462e9a4c7d0b512ef/java-squid/src/main/java/org/sonar/java/se/ConstraintManager.java#L38) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)

**Comment by SonarTech** [comment]
SonarQube analysis reported 1 issue:
* MAJOR 1 major

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* MAJOR [The Cyclomatic Complexity of this method "createSymbolicValue" is 12 which is greater than 10 authorized.](https://github.com/SonarSource/sonar-java/blob/b48a6da7c29efb8cc95330fc7b905f2aa49950a1/java-squid/src/main/java/org/sonar/java/se/ConstraintManager.java#L38) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)

**Comment by SonarTech** [comment]
SonarQube analysis reported 1 issue:
* MAJOR 1 major

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* MAJOR [The Cyclomatic Complexity of this method "createSymbolicValue" is 12 which is greater than 10 authorized.](https://github.com/SonarSource/sonar-java/blob/44633e80a7f4c7336d556f3b232052117fa0e65c/java-squid/src/main/java/org/sonar/java/se/ConstraintManager.java#L38) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)

**Comment by DidierBesset** [comment]
Any idea on how to make SonarQube happy?

**Comment by SonarTech** [comment]
SonarQube analysis reported 1 issue:
* MAJOR 1 major

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* MAJOR [The Cyclomatic Complexity of this method "createSymbolicValue" is 12 which is greater than 10 authorized.](https://github.com/SonarSource/sonar-java/blob/44633e80a7f4c7336d556f3b232052117fa0e65c/java-squid/src/main/java/org/sonar/java/se/ConstraintManager.java#L38) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)

**Pull request merged**
