### PR TITLE
fixing the String index out of range exception while parsing surefire…

### PR DESCRIPTION
**Pull request by rohitri-90**
… reports for Dynamic test cases

Please ensure your pull request adheres to the following guidelines: 

- [ ] Use the following formatting style: [SonarSource/sonar-developer-toolset](https://github.com/SonarSource/sonar-developer-toolset#code-style)
- [ ] Unit tests are passing and you provided a unit test for your fix
- [ ] ITs should pass : To run ITs locally, checkout the [README](https://github.com/SonarSource/sonar-java/blob/master/README.md) of the project.
- [ ] If there is a [Jira](http://jira.sonarsource.com/browse/SONARJAVA) ticket available, please make your commits and pull request start with the ticket number (SONARJAVA-XXXX)

### CODE REVIEW

**Comment by benzonico** [comment]
Hi, thanks for the contribution : in order for us to integrate your change : could you please provide a surefire report and a unit test for this problem ?

**Comment by rohitri-90** [comment]
Hi benzonico 
Please find the below mention surefire report and testcase snipet:
1.Surefire report:
<testcase name="block diff - IOS - Only OS Type(testGCT" classname=")" time="0.025"/>
  <testcase name="block diff - IOS - all test(testGCT" classname=")" time="0.006"/>
  <testcase name="block diff - IOS - blocks swapped(testGCT" classname=")" time="0.006"/>
  <testcase name="block diff - IOS - changes in global lines(testGCT" classname=")" time="0.036"/>
  <testcase name="block diff - IOS - compare blocks(testGCT" classname=")" time="0.006"/>
  <testcase name="block diff - IOS - empty input(testGCT" classname=")" time="0.004"/>
  <testcase name="block diff - IOS - global lines swapped(testGCT" classname=")" time="0.007"/>
  <testcase name="block diff - IOS - header removed(testGCT" classname=")" time="0.002"/>
  <testcase name="block diff - IOS - ignore blocks(testGCT" classname=")" time="0.007"/>
  <testcase name="block diff - IOS - ignore patterns(testGCT" classname=")" time="0.003"/>

2.TestCase:
@TestFactory
	public Stream<DynamicTest> testGCT() {
		File[] files = new File("src/test/resources/dynamic_testing_data/diff_test").listFiles();
		List<File> fileList = Arrays.asList(files);
		return fileList.stream()
				.map(deviceFolder -> DynamicTest.dynamicTest("block diff - " + deviceFolder.getName(), () -> {
					log.info("-------------- " + "block diff for device " + deviceFolder.getName() + " --------------");
					File baseConfig = null, actualConfig = null, template = null, diffOutput = null;
					if (deviceFolder.isDirectory()) {
						baseConfig = checkForFile("/baseConfig.txt", deviceFolder);
						actualConfig = checkForFile("/actualConfig.txt", deviceFolder);
						template = checkForFile("/template.txt", deviceFolder);
						diffOutput = checkForFile("/expected_output.txt", deviceFolder);
						
						if (baseConfig != null && actualConfig != null && template != null && diffOutput != null) {
							BlockDiffRequestV1 req = getReqObj(baseConfig, actualConfig, template);
							BlockDiffResponseV1 actualResponse = blockDiffService.getConfigBlockDiff(req);
							BlockDiffResponseV1 expectedResponse = getExpectedResponseObj(diffOutput, actualResponse.getFormat());
							FileUtil.writeFile(deviceFolder.getAbsolutePath(), actualResponse.getDiff().toString(),
									"actual_output.txt");
							assertEquals(expectedResponse, actualResponse);
						}
					}
				}));
	}

Regards
Rohit

**Comment by rohitri-90** [comment]
Adding the screenshot of surefire report section since it is not visible in my previous comment
surefire_erroe

**Comment by rohitri-90** [comment]
Hi benzonico

Any update on this?

Regards
Rohit

**Comment by benzonico** [comment]
Hi, before doing anything : could you please explain how you generate such a surefire report ? which version of junit or surefire are you using ? I would like to understand how we can have such a classname in the report before and have. Thanks.

**Comment by benzonico** [comment]
Hi, without any further explanation of the issue i'm closing this PR. 
In order for us to reopen it, please open a thread describing how we can reproduce the issue at https://community.sonarsource.com/ Thanks.

**Comment by nosakai** [comment]
Oh, I was waiting for this PR would be merged..
I believe this PR resolves the problem below.

https://community.sonarsource.com/t/gradle-plugin-does-not-tolerate-funny-surefire-output-for-junit5-dynamic-tests/1004

The problems happen on JUnit5 dynamic tests without `@Displayname`.
```
@ParameterizedTest
@MethodSource("getDatas")
void testIsValid(String datas) {
    // any tests
}
```

When you write `@DisplayName`, it works. But it's very hard to check all tests.

```
@ParameterizedTest
@MethodSource("getDatas")
@DisplayName("#isValid")
void testIsValid(String datas) {
    // any tests
}
```
Could you please reopen and merge this PR?

**Comment by benzonico** [comment]
@nosakai Thanks a lot for your message, i'll have a closer look at this with your reproducer. 
Your thread on discuss went unnotice on my side, sorry.

**Comment by nosakai** [comment]
@benzonico  Thank you so much for your prompt response!

**Pull request closed without merging**
